/*
 * This source file was generated by the Gradle 'init' task
 */
package org.numerosity.mathlib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public String testing(boolean x, boolean y, boolean z) {
        String temp = "You entered: " + x + "  " + y + " " + z;
        return temp;
    }
}
